---
name: Poetry Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Specify your desired Python version

    - name: Install Poetry
      uses: poetry/actions/install@v1
      with:
        poetry-version: 'latest' # Specify the version of Poetry you want

    - name: Install dependencies
      run: poetry install

    - name: Build the project
      run: poetry build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          dist/*